package com.chen.mapper;

import com.chen.pojo.AccountBook;
import java.util.List;

public interface AccountBookMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_book
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_book
     *
     * @mbggenerated
     */
    int insert(AccountBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_book
     *
     * @mbggenerated
     */
    AccountBook selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_book
     *
     * @mbggenerated
     */
    List<AccountBook> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_book
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AccountBook record);
}